# Save as .codeclimate.yml (note leading .) in project root directory
languages:
  JavaScript: true
exclude_paths:
  - Gruntfile.js
  - grunt/testfile.js
  - test/fixture.js
engines:
  eslint:
    enabled: true
paths:
  - index.js
  - test/**/*.js
  - lib/**/*.js

