language: node_js
node_js:
- iojs
sudo: false
env:
  global:
    secure: nu1qEfGZikmNQGrzeQOPZ1TMGADoEx9T9HaofkRlPkw0mWJwhx5Gc/cN1x3nG4J75Z7i0cBKoJ8jhsO0Gx18qPKhqxATLz/ko3pRf8TJGlcABlqsJwSO8ST+5Z00fg5OUAev9ROyU9mMwpf7DlifAEc7O2vPj6jfOxXbk0eaoNktKuKeBRQitxgc2vrJX2el6KoDiW7/+NT8Ls0qEC9YRTCOOo3/Cqopmx3CFGlCFCcffjCfBteivEUQbZ0x+lJ0WukJw9yvWe+O4LdIWRee5iMYY4FB5O9QoCD7Cz8wZ8tu/kCJzufe4f6mNnaiCiOlqvC4mE265e0mqw4+ts9sLX/OwyZsE1kWj5x0Xqg5gKrcsVFnNtuStxe+YFyBkxra8aKUh85Q4OBK/9k8o3P3zwMZHESJ9d009YtGGffPX4sl51zlef7YvfvwFjdMJkpPnfSnLXNTsuob2QzIf2BC5MjGq/dbXIQWQFuUhiTmRh5B3c24Pyw2N9hVs01qYUhx3lIEksMIfCk/8ZF/OFgRNmlwtGFIotvcjHdVt4xB4YXbXnKNiQooSdm/pEh/WSCyzlKlxkjlm4e8k62QIg2BHqcfke7+O1VysGqVzleZ+FKOUoFJo04UB0RFvRpc0HBUgSokqENjn75F+Tzm8FlVq/2U7YHsBCIcH3LUpBcSJfI=
