language: node_js
node_js:
  - iojs
sudo: false
env:
  CODACY_REPO_TOKEN:
    secure: "Zxh9pCMuTi7O43Nb3SUd4PxMekKz7MVMw0BAPsk4SJJaGVizV1bqjRjQzM69naB+9XnJ+WaO//w2E0sEPbkMqA7+s48KCFd9G75ACrKaelGPYNpacOSDLGLRQE4Hzb8cHFeluUo5t0zRmMr25TMvMXaweOcgaVzBQtTWVQEHZ6Mn3ceUxpzVdq8KWPUytUJspV2T2qlbDnwUyVFpK6SxpRBOuVliejkFYICsc41QxWSi4PVJ0wG5Oygc9FfQuKJN+28106d3WSzY3wVQCMow0AgLxlcTxQRxs4NWsDqf81z8yve68otA7N1/Pp8CSFCHe1Y7nmTK+I0gR+cdYKvbjyozxQqFNkuDdWeNR7DTPoCSq64WKbxppzqtJJewkzaj1IP8SzPaxuvj4fZjDCWxLx+kRdDm6tM2RgpsGMh2XcdZ7vE+/y8RKVM7rsHIdRVJlFhOz+yFZqUG+M2Sr2UyW7OnPBQr9IFU/FrJvJHCbuCzaCzVHFamQnD7TN77Ck0TxBOV5+Q6QeBMRhZD6Ho3xB/YZfCAc2si7+14bKeve3tmznofyZGUvektGbyz+/2uhKIuF7BpeMlLGZOeafZ4/F6k2hL4YIVqnalaBcbk3WuGdftIVMNV6rxJ46hlhNdRPVAKEDMcJGxXks9aMFzBkA/uG83QHUvfXxibU4QwvlA="
